# Generated by Django 5.0.1 on 2024-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("colour", models.CharField(max_length=20)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("cotton", "Cotton"),
                            ("blend_cotton", "Blend Cotton"),
                            ("mesh", "Mesh"),
                            ("woolen", "Woolen"),
                            ("rayon", "Rayon"),
                            ("nylon", "Nylon"),
                            ("sport", "Sport"),
                            ("gymfit", "Gymfit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "suitable_for",
                    models.CharField(
                        choices=[("Men", "Men"), ("Women", "Women")], max_length=10
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("pattern1", "Pattern 1"),
                            ("pattern2", "Pattern 2"),
                            ("pattern3", "Pattern 3"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
