# Generated by Django 5.0.1 on 2024-02-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "any_disease",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allergies", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
